# Generated by Django 3.1.5 on 2021-01-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('paper_attrs', '0001_initial'),
        ('author_attrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='paper_scientific',
            field=models.ManyToManyField(blank=True, to='paper_attrs.ScientificArea', verbose_name='Области науки'),
        ),
        migrations.AddField(
            model_name='author',
            name='paper_subject',
            field=models.ManyToManyField(blank=True, to='paper_attrs.Subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='author',
            name='paper_type',
            field=models.ManyToManyField(blank=True, to='paper_attrs.PaperType', verbose_name='Типы работ'),
        ),
        migrations.AddField(
            model_name='author',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='author_attrs.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='author',
            name='scientific_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='author_attrs.scientificrank', verbose_name='Ученая степень'),
        ),
    ]
