# Generated by Django 3.1.5 on 2021-01-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_attrs', '0001_initial'),
        ('accounts', '0002_auto_20210125_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paper_scientific',
            field=models.ManyToManyField(blank=True, to='paper_attrs.ScientificArea', verbose_name='Области науки'),
        ),
        migrations.AlterField(
            model_name='author',
            name='paper_subject',
            field=models.ManyToManyField(blank=True, to='paper_attrs.Subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='paper_type',
            field=models.ManyToManyField(blank=True, to='paper_attrs.PaperType', verbose_name='Типы работ'),
        ),
    ]
