# Generated by Django 3.1.5 on 2021-01-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_attrs', '0001_initial'),
        ('accounts', '0003_auto_20210126_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_author',
            field=models.ManyToManyField(blank=True, to='paper_attrs.PaperType', verbose_name='Любимый автор'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Денежный баланс'),
        ),
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='author',
            name='faculity',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учебное заведение'),
        ),
    ]
