# Generated by Django 3.1.5 on 2021-01-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус закза',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='ScientificArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область науки',
                'verbose_name_plural': 'Области науки',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paper.scientificarea', verbose_name='Область науки')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ReadyPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_slug', models.SlugField(max_length=240)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('path', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('intro', models.TextField(verbose_name='Введение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('references', models.TextField(verbose_name='Список литературы')),
                ('fragment', models.TextField(verbose_name='Отрывок')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Опубликованно')),
                ('viewed', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('buyed', models.IntegerField(default=0, verbose_name='Куплена')),
                ('originality', models.FloatField(default=0, verbose_name='Оригинальность')),
                ('scientific', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.scientificarea', verbose_name='Область науки')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Готовая работа',
                'verbose_name_plural': 'Готовые работы',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_slug', models.SlugField(max_length=240)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('path', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('wishes', models.CharField(blank=True, max_length=200, verbose_name='Пожелания')),
                ('scientific', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.scientificarea', verbose_name='Область науки')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paper.orderstatus', verbose_name='Статус')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Заказ на работу',
                'verbose_name_plural': 'Заказы на работу',
            },
        ),
    ]
