# Generated by Django 3.1.5 on 2021-01-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_attrs', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedpaper',
            name='path',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='orderedpaper',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='ordered_paper', serialize=False, to='paper_attrs.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='readypaper',
            name='path',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='readypaper',
            name='release_date',
            field=models.DateField(auto_now_add=True, verbose_name='Опубликованно'),
        ),
    ]
