# Generated by Django 3.1.5 on 2021-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpaper',
            name='title_slug',
        ),
        migrations.RemoveField(
            model_name='readypaper',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='orderedpaper',
            name='slug',
            field=models.SlugField(max_length=240, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='readypaper',
            name='slug',
            field=models.SlugField(max_length=240, null=True, unique=True),
        ),
    ]
