# Generated by Django 3.1.5 on 2021-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20210119_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedpaper',
            name='slug',
            field=models.SlugField(default='', max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='readypaper',
            name='slug',
            field=models.SlugField(default='', max_length=240, unique=True),
        ),
    ]
